name: Release Helm Chart
permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - master
    paths:
      - '.helm-chart/**'
      - '.github/workflows/helm-publish.yml'

jobs:
  publish-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latestcode
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.13.0  # Use the latest Helm v3 release

      - name: Package Helm chart
        run: |
          helm package ./.helm-chart
          echo "CHART_FILE=$(ls *.tgz)" >> $GITHUB_ENV  # Pass the chart file name to the next step

      - name: Create GitHub Release and Upload Helm Chart
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-release
          release_name: Release ${{ github.sha }}
          files: ${{ env.CHART_FILE }}

